version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    labels:
      - dependencies
      - patch
      - skip-changelog
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: daily
    labels:
      - dependencies
      - patch
      - skip-changelog
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
